### ISSUE TITLE
Could KtDeserializer extend com.googleprotobuf.Parser?

### ISSUE THREAD

**Issue by mcpiroman** [open-toast/protokt#139]
They both serve the same purpose anyway.

My use case is that for my own messages I can only get `KtDeserializer`, but for others, including the stdlib ones like `com.google.Empty`, I can only get `Parser`. Therefore it is quite difficult to work with both in a generic context.

Alternatively, maybe create some wrapper that will convert `Parser` into `KtDeserializer` or some other abstraction.

EDIT: Actually I don't think there is a need for `KtDeserializer` at all as it doesn't add anything on its own, just hinders interoperability with protobuf.

**Comment by andrewparmet** [comment]
While they serve the same purpose, `com.google.protobuf.Parser` is only available on the JVM, so we'd have to remove any dependency on it if we want to support Kotlin multiplatform one day. Today we only have dependencies on `CodedInputStream` and `CodedOutputStream` which will be simpler to remove. `Parser` many additional methods that we'd have to implement and some of them are specific to proto2 which we don't support.

Protokt ships definitions of the base types (`google.protobuf.Empty`, etc.) with its runtime library if you need to use them, but they do not implement protobuf-java interfaces for the same reasons.

If you need seamless interoperability with Google's protobuf libraries, you might consider the [official Kotlin bindings](https://developers.google.com/protocol-buffers/docs/kotlintutorial). Otherwise I'd recommend defining an interface with the shared behavior between `KtDeserializer` and `Parser`. If there are methods on `Parser` that you think would be helpful to have on `KtDeserializer` then we'd welcome the API suggestions.

**Comment by mcpiroman** [comment]
> Protokt ships definitions of the base types (google.protobuf.Empty)

Oh ok, this will do for me, thanks!

>  shared behavior between KtDeserializer and Parser

This approach wouldn't be possible for external types, because `KtDeserializer` requires `T : KtMessage`.

Quite strange that the protobuf itself doesn't share that much between languages, but if so then the multiplatform argument is legit.

**Comment by andrewparmet** [comment]
A shared interface is helpful, for example, when moving from bytes to any concrete type:

```kotlin
interface MessageParser<T> {
    parse(bytes: ByteArray): T
}

interface ProtoktParser<T : KtMessage> : MessageParser<T>

interface ProtobufJavaParser<T : MessageLite> : MessageParser<T>
```
