### ISSUE TITLE
Confusion over proto imports

### ISSUE THREAD

**Issue by RaphaelTarita** [open-toast/protokt#96]
Hi!

I recently came over this project and I am very happy to use it my own project. It is a wonderful replacement for plain java protoc and I'm delighted that I can use the kotlin builder pattern instead of java-like builders. But concerning these similarities and differences between protoc-java and protokt, I came over a case that I am not sure about.

The main question is: How does protokt handle protobuf imports from the same project?

The protobuf documentation [mentions in one single line](https://developers.google.com/protocol-buffers/docs/proto3#importing_definitions) that imports are not available in Java. I have not found any other information about why that is or what one should do instead. But I was interested whether imports are available in protokt. So I tested the following setup:

```
package.root.core.watcher.
                          A.proto
                          B.proto
```

where `A.proto` contains

```protobuf
syntax = "proto3";

package package.root.core.watcher;

message A {
  string str = 1;
}
```

and `B.proto` contains

```protobuf
syntax = "proto3";

package package.root.core.watcher;

import "package/root/core/watcher/A.proto";

message B {
  string str = 1;
  A aValue = 2;
}
```
Of course, `package.root` is just a placeholder for the actual package root. It might also be worth noting that the IntelliJ plugin "Protocol Buffer Editor" recognizes the import just fine.

Now, when I run the `:generateProto` gradle task, I get the following output:

```
Executing task 'generateProto'...

Starting Gradle Daemon...
Gradle Daemon started in 1 s 58 ms
> Task :extractIncludeProto UP-TO-DATE
> Task :extractProto UP-TO-DATE
> Task :generateProto FAILED
3 actionable tasks: 1 executed, 2 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateProto'.
> protoc: stdout: . stderr: msw/server/core/watcher/A.proto: File not found.
  main/kotlin/msw/server/core/watcher/B.proto:5:1: Import "msw/server/core/watcher/A.proto" was not found or had errors.
  main/kotlin/msw/server/core/watcher/B.proto:9:3: "msw.server.core.watcher.A" seems to be defined in "main/kotlin/msw/server/core/watcher/A.proto", which is not imported by "main/kotlin/msw/server/core/watcher/B.proto".  To use it here, please add the necessary import.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
```

What confuses me is that it neither works nor gives me a hint that imports are not available in protokt. I can't really be sure whether protokt just doesn't support imports or there is some weird bug involved. The output tells me that 1. the file was not found (but it is right there, so that's not true) and 2. that the import is missing (but it's also right there).

Does protokt support protobuf imports? If yes, what am I doing wrong? And if no, I think it should show a corresponding error message instead of complaining about missing files and imports which are right there.

Thank you very much!

**Comment by andrewparmet** [comment]
I'm not sure what the documentation means by "not available in Java" as I've used imports across files in protobuf with Java generation. Perhaps it's referring to the `import public` technique, which I've never seen before.

The error you're seeing is actually happening before protokt has actually gotten a handle on code to generate - that's coming from protoc itself. To me it looks like your proto files are set up properly in terms of their contents, but the hint from protoc suggests that `A.proto` might be in the wrong place. It looks like it's in `src/main/kotlin` instead of `src/main/proto`. This disagrees with the implicit _file_ structure at the beginning of your post, even if the _package_ structure is correct.

Can you verify that `A.proto` and `B.proto` are both in `src/main/proto/package/root/core/watcher`? (The error message mentions `msw.server.core.watcher` but I'm assuming that's what the placeholder was for?)

Note that proto files declared to be in the same package do not actually have to be in directories with the package name file structure although that's generally recommended practice. The import has to reference the file location, not the package declaration. These match if you follow the package structure in the directory structure.

**Comment by RaphaelTarita** [comment]
You are right, I had my proto files in the `kotlin` folder structure instead of  `proto`. Changing this solved the issue. I was very confused by that one line of the ProtoBuf documentation where it says that imports are "not available" in Java (because they apparently are). I just assumed that I was getting these errors because they might as well be not available in protokt.

Now it makes more sense to me, thank you for the explanation!
